#!/bin/bash
DOCKER_REPOSITORY_HOST=registry.cn-beijing.aliyuncs.com
DOCKER_REPOSITORY_USERNAME=用户名
DOCKER_REPOSITORY_PASSWORD=密码
DOCKER_IMAGE_NAME=仓库/镜像名
DOCKER_IMAGE_VERSION=版本号

CURR_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION=1.0.3}
REPOSITORY=${DOCKER_REPOSITORY_HOST}/${CURR_IMAGE}

docker build -t ${CURR_IMAGE} .
docker tag ${CURR_IMAGE} ${REPOSITORY}
docker login --username=${DOCKER_REPOSITORY_USERNAME} --password=${DOCKER_REPOSITORY_PASSWORD}  ${DOCKER_REPOSITORY_HOST}
docker push ${REPOSITORY}
